snsnet/net/urls.py
from django.conf.urls import url
from . import views

app_name = 'net'

urlpatterns = [

    # redirects to the login page
    # ex: /
    url(r'^$', views.login_redirect, name='login_redirect'),

    # ex: /login/
    url(r'^login/$', views.login_account, name='login_account'),

    # ex: /signup/
    url(r'^health_professional_signup/$', views.health_professional_signup,
        name='health_professional_signup'),

    # ex: /signup/
    url(r'^health_institution_signup/$', views.health_institution_signup,
        name='health_institution_signup'),

    # ex: /resend_email/
    url(r'^resend_email/$', views.resend_email, name='resend_email'),

    # ex: /feed/
    url(r'^feed/$', views.feed, name='feed'),

    # ex: /account/username
    url(r'^account/(?P<username>[\w\-]+)/$', views.account, name='account'),

    # ex: /logout/
    url(r'^logout/$', views.logout_account, name='logout_account'),

    # ex: /upload_image/
    url(r'^upload_image/$', views.upload_image, name='upload_image'),

    # ex: /update_personal_info/
    url(r'^update_personal_info/$', views.update_personal_info,
        name='update_personal_info'),

    # ex: /follow/username
    url(r'^follow/(?P<username>[\w\-]+)/$', views.follow, name='follow'),

    # ex: /unfollow/username
    url(r'^unfollow/(?P<username>[\w\-]+)/$', views.unfollow, name='unfollow'),

    # ex: /not_found/
    url(r'^not_found/$', views.not_found, name='not_found'),

    # ex: /search/
    url(r'^search/$', views.search, name='search'),

    # ex: /like/
    url(r'^like/$', views.like, name='like'),

    # ex: /delete_post/
    url(r'^delete_post/(?P<post_id>[0-9]+)/$',
        views.delete_post, name='delete_post'),

    # ex: /update_password/
    url(r'^update_password/$', views.update_password, name='update_password'),

]

snsnet/snsnet/urls.py
from django.contrib import admin
from django.urls import path, include
from django_email_verification import urls as email_urls

urlpatterns = [
    path('', include('net.urls')),
    path('admin/', admin.site.urls),
    path('verification/', include(email_urls)),
]

snsnet/net/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
import datetime


class Health_Institution(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    district = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.IntegerField(unique=True)
    photo = models.ImageField(upload_to='images/', blank=True)
    type = models.CharField(max_length=20)


class Health_Professional(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    photo = models.ImageField(upload_to='images/', blank=True)
    phone = models.IntegerField(unique=True)
    gender = models.CharField(max_length=20)
    district = models.CharField(max_length=100)
    work = models.ForeignKey(
        Health_Institution, on_delete=models.CASCADE, null=True, related_name='work')
    type = models.CharField(max_length=20)

    following_prof = models.ManyToManyField(
        'Health_Professional', related_name='%(class)s_following')
    following_inst = models.ManyToManyField(
        'Health_Institution', related_name='%(class)s_following')


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=500)
    image = models.ImageField(upload_to='images/', blank=True)
    likes = models.IntegerField(default=0)
    inst_likers = models.ManyToManyField(
        'Health_Institution', related_name='%(class)s_workers')
    prof_likers = models.ManyToManyField(
        'Health_Professional', related_name='%(class)s_workers')
    time = models.DateTimeField('Data de publicação')

    def is_recent(self):
        return self.time >= timezone.now() - datetime.timedelta(days=2)

snsnet/net/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import Health_Institution, Health_Professional, Post
from django.db import IntegrityError
from django_email_verification import send_email
from django.utils import timezone
from django.db.models import Value as V
from django.db.models.functions import Concat
import datetime


def login_redirect(request):
    """
    redirects to the login page
    :param request: session request
    """
    user = request.user
    if user.is_authenticated:
        return HttpResponseRedirect(reverse('net:feed'))
    else:
        return HttpResponseRedirect(reverse('net:login_account'))


def login_account(request):
    """
    if the form hasn't been filled: the login template is returned
    if the form has been filled: the login operation is performed and the feed template is returned
    :param request: session request
    """
    if request.method == 'POST':

        inputUsername = request.POST.get('inputUsername')
        inputPassword = request.POST.get('inputPassword')
        user = authenticate(request, username=inputUsername,
                            password=inputPassword)

        if user is not None and user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('net:feed'))

        else:
            return render(request, 'net/login.html', {'error_message': "username ou password inválidos"})

    else:
        return render(request, 'net/login.html')


def health_professional_signup(request):
    """
    if the form hasn't been filled: the signup_health_professional template is returned
    if the form has been filled: the health professional account is created and an email verification is sent
    :param request: session request
    """
    if request.method == 'POST':

        first_name = request.POST.get('inputFirstName')
        last_name = request.POST.get('inputLastName')
        user_name = request.POST.get('inputUsername')
        email = request.POST.get('inputEmail')
        phone = request.POST.get('inputPhone')
        gender = request.POST.get('gender')
        district = request.POST.get('district')
        prof_type = request.POST.get('type')
        work = request.POST.get('work')
        password = request.POST.get('inputPassword')
        conf = request.POST.get('inputPasswordConfirmation')

        if '.' in user_name:
            error_message = 'o username contem um caracter inválido'
            institutions = Health_Institution.objects.all()
            return render(request, 'net/signup_health_professional.html', {'error_message': error_message,
                                                                           'institutions': institutions})

        if password != conf:
            error_message = 'as palavras-passe não coincidem'
            institutions = Health_Institution.objects.all()
            return render(request, 'net/signup_health_professional.html', {'error_message': error_message,
                                                                           'institutions': institutions})

        if gender == 'género' or district == 'distrito' or prof_type == 'tipo de profissional' \
                or work == 'onde trabalha':
            error_message = 'preenche corretamente os campos'
            institutions = Health_Institution.objects.all()
            return render(request, 'net/signup_health_professional.html', {'error_message': error_message,
                                                                           'institutions': institutions})

        try:
            user = User.objects.create_user(username=user_name, email=email, password=password,
                                            first_name=first_name, last_name=last_name, is_active=False)

        except IntegrityError:
            error_message = 'Este utilizador já está registado'
            institutions = Health_Institution.objects.all()
            return render(request, 'net/signup_health_professional.html', {'error_message': error_message,
                                                                           'institutions': institutions})

        if work == 'null':
            acc = Health_Professional()
            acc.user = user
            acc.phone = phone
            acc.gender = gender
            acc.district = district
            acc.type = prof_type
            acc.save()

        else:
            work = get_object_or_404(Health_Institution, pk=work)
            acc = Health_Professional()
            acc.user = user
            acc.phone = phone
            acc.gender = gender
            acc.district = district
            acc.type = prof_type
            acc.work = work
            acc.save()

        send_email(user)
        return render(request, 'net/email_sent.html', {'account': acc})

    else:
        institutions = Health_Institution.objects.all()
        return render(request, 'net/signup_health_professional.html', {'institutions': institutions})


def health_institution_signup(request):
    """
    if the form hasn't been filled: the signup_health_institution template is returned
    if the form has been filled: the health institution account is created and an email verification is sent
    :param request: session request
    """
    if request.method == 'POST':
        name = request.POST.get("inputName")
        user_name = request.POST.get('inputUsername')
        email = request.POST.get('inputEmail')
        phone = request.POST.get('inputPhone')
        district = request.POST.get('district')
        inst_type = request.POST.get('type')
        address = request.POST.get('inputAddress')
        password = request.POST.get('inputPassword')
        conf = request.POST.get('inputPasswordConfirmation')

        if password != conf:
            error_message = 'as palavras-passe não coincidem'
            return render(request, 'net/signup_health_institution.html', {'error_message': error_message})

        if inst_type == 'tipo de instituição' or district == 'distrito':
            error_message = 'preenche corretamente os campos'
            return render(request, 'net/signup_health_institution.html', {'error_message': error_message})

        try:
            user = User.objects.create_user(username=user_name, email=email, password=password,
                                            first_name=name, is_active=False)

        except IntegrityError:
            error_message = 'Esta instituição já está registada'
            return render(request, 'net/signup_health_institution.html', {'error_message': error_message})

        acc = Health_Institution()
        acc.user = user
        acc.district = district
        acc.address = address
        acc.phone = phone
        acc.type = inst_type
        acc.save()

        send_email(user)
        return render(request, 'net/email_sent.html')

    else:
        return render(request, 'net/signup_health_institution.html')


def resend_email(request):
    """
    resends the verification email if user is inactive
    :param request: session request
    """
    if request.method == 'POST':
        email = request.POST.get('inputEmail')

        try:
            user = User.objects.get(email=email)

        except ObjectDoesNotExist:
            return render(request, 'django_email_verification/confirmation.html', {
                'error_message': 'o email indicado nao está associado a nenhuma conta'
            })

        if user is not None:

            if not user.is_active:
                send_email(user)
                return render(request, 'net/email_sent.html')

            else:
                return render(request, 'django_email_verification/confirmation.html', {
                    'error_message': 'o email indicado já foi verificado'
                })
    else:
        return HttpResponseRedirect(reverse('net:login_account'))


def feed(request):
    """
    opens the feed page if the user is logged in
    :param request: session request
    """
    user = request.user
    if user.is_authenticated:
        acc = get_account(user)

        institution = False
        professional = False

        if isinstance(acc, Health_Professional):
            posts = get_posts_of_following(acc)
            professional = True
        else:
            posts = get_posts_of_institution_workers(acc)
            institution = can_post(acc)

        if request.method == 'POST':

            post = Post()
            post.user = acc.user
            post.likes = 0
            post.time = timezone.now()

            if isinstance(acc, Health_Professional):

                title = request.POST.get('title')

                if not title:
                    return render(request, 'net/feed.html', {'no_title': 'o post tem que ter um título',
                                                             'account': acc, 'posts': posts,
                                                             'institution': institution, 'professional': professional})
                post.title = title

                content = request.POST.get('content')
                image = request.FILES.get('image')

                if image is not None:
                    if not is_valid_image(str(image)):
                        return render(request, 'net/feed.html', {'invalid_image': 'formato de imagem inválido',
                                                                 'account': acc, 'posts': posts,
                                                                 'institution': institution,
                                                                 'professional': professional})
                    else:
                        post.image = image

                if content is not None:

snsnet/net/templates/net/account_general.html
{% extends "net/header.html" %}

{% block page_name %}
{{ visited.user.first_name }} {{ visited.user.last_name }}
{% endblock %}

{% block new_image_css %}
{% load static %}
<!--<link rel="stylesheet" href="{% static 'net/css/new_image.css' %}">-->
{% endblock %}

{% block content %}

{% load static %}
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->

      <div class="card my-4 text-center border-success">

        <h5 id="username" class="card-header">{{ visited.user.username }}</h5>

        {% if visited.photo %}
        <br><img src="{{ visited.photo.url }}" class="rounded-circle mx-auto d-block" width="250" height="250"><br>
        {% else %}
        <img src="{% static 'net/assets/img/perfil.png' %}" class="rounded-circle mx-auto d-block" width="250"
          height="250">
        {% endif %}

        <div class="d-grid gap-2 col-6 mx-auto">
          {% if account.user.id != visited.user.id %}
          {% if follow %}
          <br><a href="{% url 'net:follow' visited.user.username %}"
            class="btn btn-success btn-sm card-body">Seguir</a><br>
          {% elif unfollow %}
          <br><a href="{% url 'net:unfollow' visited.user.username %}" class="btn btn-success btn-sm card-body">Deixar
            de seguir</a><br>
          {% endif %}
          {% endif %}
        </div>

        <h1 id="name">{{ visited.user.first_name }} {{ visited.user.last_name }}</h1>

        {% if work %}
        <a href="{% url 'net:account' visited.work.user.username %}" class="nav-link text-success">
          <h5 class="work">{{ visited.work.user.get_full_name }}</h5>
        </a>
        {% endif %}

        <h7 id="district">{{ visited.district }}, Portugal</h7>

        {% if account.user.id == visited.user.id %}
        <br>
        <div class="d-grid gap-2 col-6 mx-auto">
          <button class="btn btn-outline-success btn-sm card-body" data-bs-toggle="modal"
            data-bs-target="#new_photo_modal">Carregar imagem</button><br>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
          <a href="{% url 'net:update_personal_info' %}" class="btn btn-outline-success btn-sm card-body">Alterar
            dados</a><br>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
          <a href="{% url 'net:update_password' %}" class="btn btn-outline-success btn-sm card-body">Alterar
            password</a><br>
        </div>
        {% endif %}

      </div>

      <div id="posts_card" class="card my-4 border-success">
        <h5 class="card-header">Contactos</h5>
        <h7 class="card-body"><strong>e-mail:</strong> {{ visited.user.email }}</h7>
        <h7 class="card-body"><strong>telefone:</strong> {{ visited.phone }}</h7>
      </div>

    </div>

    <div class="col-md-8">

      {% if posts %}
      {% for post, author, liked in posts %}

      <div class="card mb-4 border-success">
        <div class="card-header text-muted">

          {% if author.photo %}
          <img src="{{ author.photo.url }}" class="rounded-circle" width="35" height="35">
          {% else %}
          <img src="{% static 'net/assets/img/perfil.png' %}" class="rounded-circle" width="35" height="35">
          {% endif %}

          <a href="{% url 'net:account' post.user.username %}" id="post_author" class="text-success">
            <strong>{{ post.user.first_name }} {{ post.user.last_name }}</strong> </a> <br>


        </div>
        <div class="card-body">
          <h4 class="card-title">{{ post.title }}</h4>
          <p class="card-text">{{ post.content }}</p>
          {% if post.image %}
          <img src="{{ post.image.url }}" width="600"><br>
          {% endif %}
          <br>
          <h10 class="text-secondary">{{ post.time }}</h10>
        </div>

        <div class="card-footer text-muted">
          <div class="container">
            <div class="row">
              <div class="col-10">
                <button class="btn" id="like{{ post.id }}" name="{{ post.id }}" style="display: inline-block;">

                  <svg id="like_true{{ post.id }}" xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                    fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16" style="display:none">
                    <path fill-rule="evenodd"
                      d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                  </svg>

                  <svg id="like_false{{ post.id }}" xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                    fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16" style="display:none">
                    <path
                      d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                  </svg>

                </button>

                <label id="like_count{{ post.id }}">
                  {{ post.likes }} likes
                </label>

              </div>

              {% if account.user.id == visited.user.id %}

              <div class="col-2">
                <a href="{% url 'net:delete_post' post.id %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="dark "
                    class="bi bi-trash text-end" viewBox="0 0 16 16">
                    <path
                      d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                    <path fill-rule="evenodd"
                      d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                  </svg>
                </a>
              </div>

              {% endif %}

            </div>

          </div>

        </div>

      </div>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

      <script type="text/javascript">

        function validate_like(liked, id) {
          if (liked == "False") {
            document.getElementById("like_true".concat(id)).style.display = "none";
            document.getElementById("like_false".concat(id)).style.display = "block";
          } else {
            document.getElementById("like_true".concat(id)).style.display = "block";
            document.getElementById("like_false".concat(id)).style.display = "none";
          }
        }

        $(document).ready(function () {

          $("#like{{ post.id }}").click(function () {
            $.ajax({
              url: "{% url 'net:like' %}",
              type: 'GET',
              data: {
                post_id: $(this)[0].getAttribute("name")
              },
              success: function (response) {
                validate_like(response.liked, "{{ post.id }}")
                $("#like_count{{ post.id }}").text(response.likes + ' likes')
              }
            })
          })

        })

        var liked = "{{ liked }}";
        var id = "{{ post.id }}";
        validate_like(liked, id);
      </script>

      {% endfor %}
      {% else %}

      <div class="card my-4 text-center">
        <br>
        <h4 style="color: grey;">Parece que não há posts recentes</h4>
        <br>

      </div>

      {% endif %}

    </div>

  </div>

</div>

<!--add new photo modal-->

<div class="modal fade" id="new_photo_modal" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body text-center">
        <div class="container">
          <div class="row">
            <form method="post" enctype="multipart/form-data" action="{% url 'net:upload_image' %}">
              {% csrf_token %}
              <div class="form-group files">
                <label>Escolhe a tua imagem</label><br><br>
                <input type="file" class="form-control" name="image"><br>
                <input type="submit" class="btn btn-success" placeholder="Carregar">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- add new photo modal -->

<div class="modal fade" id="change_data_modal" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body text-center">
        <div class="container">
          <div class="row">
            <form method="post" enctype="multipart/form-data" action="{% url 'net:update_personal_info' %}">
              {% csrf_token %}
              <label>Altera os teus dados</label><br><br>
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input name="username" type="text" class="form-control" placeholder="{{ account.user.username }}"
                  aria-label="Username" aria-describedby="basic-addon1">
              </div>
              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text" id="basic-addon2">email</span>
                </div>
                <input type="text" class="form-control" aria-describedby="basic-addon2"
                  placeholder="{{ account.user.email }}">
              </div>
              <input id="update_personal_info" type="submit" class="btn btn-success" placeholder="Carregar">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

snsnet/net/templates/net/data_updated.html
{% extends 'net/initial_template.html' %}

{% block title %}
dados alterados
{% endblock %}

{% block content %}

<div class="text-center d-grid gap-2">
    <a href="{% url 'net:login_account' %}" role="button" class="btn btn-success btn-lg">FAZER LOGIN</a>
</div>

{% endblock %}

snsnet/net/templates/net/email_sent.html
{% extends 'net/initial_template.html' %}

{% block title %}
enviámos-te um email de confirmação
{% endblock %}

{% block content %}
<div class="text-center">
    <h2 class="login-heading mb-4">o token de ativação ficará disponível durante dois minutos. Apressa-te!</h2>
</div>

{% endblock %}

snsnet/net/templates/net/header.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>{% block page_name %} {% endblock %}</title>
  <link rel="icon" href="https://www.sns.gov.pt/wp-content/themes/sns/images/favicon/favicon_sns.svg" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'net/css/account.css' %}">
  {% block new_image_css %}{% endblock %}
</head>

<body>

  <nav class="px-3 py-2 bg-success text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'net:feed' %}"
          class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
          <img src="https://www.sns.gov.pt/wp-content/uploads/2016/04/LOGO-copy.png" alt="" width="40" height="40">
        </a>

        <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
          <li>
            <a href="{% url 'net:feed' %}" class="nav-link text-white">
              <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-list"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                  d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
              </svg><br>
              feed
            </a>
          </li>

          <li>
            <a href="{% url 'net:account' account.user.username %}" class="nav-link text-white">
              {% if account.photo %}
              <img src="{{ account.photo.url }}" class="rounded-circle" width="35" height="35">
              {% else %}
              <img src="{% static 'net/assets/img/perfil.png' %}" class="rounded-circle" width="35" height="35">
              {% endif %}
              <br>perfil
            </a>
          </li>
          <li>
            <a href="{% url 'net:logout_account' %}" class="nav-link text-white">
              <svg id="logout_svg" xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor"
                class="bi bi-door-closed-fill" viewBox="0 0 16 16">
                <path
                  d="M12 1a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2a1 1 0 0 1 1-1h8zm-2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
              </svg><br>
              logout
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %} {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>

</body>

</html>

snsnet/net/templates/net/login.html
{% extends 'net/initial_template.html' %}

{% block title %}
bem vindo de volta!
{% endblock %}

{% block content %}
<form method="post">

  <div class="mb-3">
        {% csrf_token %}
         <input type="text" class="form-control" placeholder="nome de utilizador" name="inputUsername">
    </div>

  <div class="mb-3">
        {% csrf_token %}
         <input type="password" class="form-control" placeholder="password" name="inputPassword">
    </div>

  {% if error_message %}
  <div class="text-center" id="error">
    <svg style="color:#d14949" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
      class="bi bi-x-circle-fill" viewBox="0 0 16 16">
      <path
        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z" />
    </svg>
    <label style="color:#d14949">{{ error_message }}</label>
  </div>
  {% endif %}
  <br>
  <button id="login_btn"
    class="btn col-12 mx-auto btn-lg btn-success btn-block text-uppercase font-weight-bold mb-2"
    type="submit">entrar
  </button>
</form>
<br>
<!-- Button trigger modal -->
<div class="text-center">
  <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal"
    data-bs-target="#signup_modal">
    ainda não tenho conta!
  </button>
</div>
{% endblock %}

{% block modal %}
<div class="modal fade" id="signup_modal" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body text-center">
        <div class="container-fluid">
          <div class="row">
            <h5 class="card-title" id="staticBackdropLabel"><br>queres criar conta em que tipo de perfil?</h5>
            <br><br><br><br>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="card text-dark bg-light mb-3 text-center">
                <div class="card-body">
                  <strong>Profissionais de Saúde</strong><br><br>
                  <p class="card-text">Uma plataforma que facilita a comunicação entre médicos,
                    enfermeiros
                    e
                    auxiliares de saúde em alturas de máxima exigência.</p><br>
                  <div class="d-grid gap-2">
                    <a href="{% url 'net:health_professional_signup' %}" class="btn btn-success">criar conta</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="card text-dark bg-light mb-3 text-center">
                <div class="card-body">
                  <strong>Instituições de Saúde</strong><br><br>
                  <p class="card-text">A mais útil e prática maneira dos hospitais e centros de saúde terem intereção
                    com os
                    seus médicos, enfermeiros e auxiliares de saúde.</p><br>
                  <div class="d-grid gap-2">
                    <a href="{% url 'net:health_institution_signup' %}" class="btn btn-success">criar conta</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
  var myModal = document.getElementById('myModal')
  var myInput = document.getElementById('myInput')

  myModal.addEventListener('shown.bs.modal', function () {
    myInput.focus()
  })
</script>
{% endblock %}